default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV.fetch('RAILS_MYSQL_USER') { 'root' } %>
  password: <%= ENV['RAILS_MYSQL_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch('RAILS_MYSQL_DATABASE') { 'blazar_db_dev' } %>
  host: 127.0.0.1
  local_infile: true

test:
  <<: *default
  database: blazar_db_test
  host: 127.0.0.1
  local_infile: true
  idle_timeout: 0
